import BottomNav from '#/shared/components/BottomNav'
import { DiscogsRateLimitDevTools } from '#/shared/components/DiscogsRateLimitDevTools'
import Header from '#/shared/components/Header'
import { PwaUpdateBanner } from '#/shared/components/PwaUpdateBanner'
import { TanStackDevtools } from '@tanstack/react-devtools'
import type { QueryClient } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import {
  HeadContent,
  Outlet,
  Scripts,
  createRootRouteWithContext,
} from '@tanstack/react-router'
import { TanStackRouterDevtoolsPanel } from '@tanstack/react-router-devtools'

import { sessionUserQueryOptions } from '#/features/auth/auth.queries'
import { DefaultCatchBoundary } from '#/shared/components/DefaultCatchBoundary'
import { NotFound } from '#/shared/components/NotFound'
import { startupImageLinks } from '#/shared/utils/startup-images'
import appCss from '../styles.css?url'

type User = { username: string }

const THEME_INIT_SCRIPT = `(function(){try{var stored=window.localStorage.getItem('theme');var mode=(stored==='light'||stored==='dark'||stored==='auto')?stored:'auto';var prefersDark=window.matchMedia('(prefers-color-scheme: dark)').matches;var resolved=mode==='auto'?(prefersDark?'dark':'light'):mode;var root=document.documentElement;root.classList.remove('light','dark');root.classList.add(resolved);if(mode==='auto'){root.removeAttribute('data-theme')}else{root.setAttribute('data-theme',mode)}root.style.colorScheme=resolved;}catch(e){}})();`

export const Route = createRootRouteWithContext<{
  queryClient: QueryClient
  user: User | null
}>()({
  beforeLoad: async ({ context }) => {
    const sessionUser = await context.queryClient.fetchQuery(
      sessionUserQueryOptions,
    )
    return { user: sessionUser ? { username: sessionUser.username } : null }
  },
  head: () => ({
    meta: [
      { charSet: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { title: 'Sillon' },
      { name: 'application-name', content: 'Sillon' },
      { name: 'mobile-web-app-capable', content: 'yes' },
      // Mirrors --background in styles.css (light / dark)
      {
        name: 'theme-color',
        content: '#f5f5f3',
        media: '(prefers-color-scheme: light)',
      },
      {
        name: 'theme-color',
        content: '#0e0e0d',
        media: '(prefers-color-scheme: dark)',
      },
      { name: 'apple-mobile-web-app-capable', content: 'yes' },
      {
        name: 'apple-mobile-web-app-status-bar-style',
        content: 'black-translucent',
      },
      { name: 'apple-mobile-web-app-title', content: 'Sillon' },
    ],
    links: [
      // Must match the latin @font-face src in styles.css
      {
        rel: 'preload',
        href: '/fonts/familjen-grotesk-latin.woff2',
        as: 'font',
        type: 'font/woff2',
        crossOrigin: 'anonymous',
      },
      {
        rel: 'preload',
        href: '/fonts/martian-mono-latin.woff2',
        as: 'font',
        type: 'font/woff2',
        crossOrigin: 'anonymous',
      },
      { rel: 'stylesheet', href: appCss },
      { rel: 'manifest', href: '/manifest.webmanifest' },
      { rel: 'icon', href: '/favicon.ico', sizes: '32x32' },
      { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' },
      { rel: 'apple-touch-icon', href: '/icons/apple-touch-icon.png' },
      // Always dark, whatever the theme; generated by generate:pwa-assets
      ...startupImageLinks(),
    ],
  }),
  errorComponent: (props) => {
    return (
      <RootDocument>
        <DefaultCatchBoundary {...props} />
      </RootDocument>
    )
  },
  notFoundComponent: () => <NotFound />,
  component: RootComponent,
})

function RootComponent() {
  return (
    <RootDocument>
      <Outlet />
    </RootDocument>
  )
}

function RootDocument({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
        <HeadContent />
      </head>
      <body className="font-sans antialiased wrap-anywhere selection:bg-foreground/15">
        <div vaul-drawer-wrapper="" className="min-h-svh bg-background">
          <PwaUpdateBanner />
          <Header />
          {children}
          <BottomNav />
          <TanStackDevtools
            config={{
              position: 'bottom-right',
            }}
            plugins={[
              {
                name: 'Tanstack Router',
                render: <TanStackRouterDevtoolsPanel />,
              },
            ]}
          />
          <ReactQueryDevtools buttonPosition="bottom-left" />
          <DiscogsRateLimitDevTools />
        </div>
        <Scripts />
      </body>
    </html>
  )
}
