/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedWantlistRouteImport } from './routes/_authenticated/wantlist'
import { Route as AuthenticatedCollectionRouteImport } from './routes/_authenticated/collection'
import { Route as AuthenticatedWantlistIdRouteImport } from './routes/_authenticated/wantlist_.$id'
import { Route as AuthenticatedCollectionIdRouteImport } from './routes/_authenticated/collection_.$id'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWantlistRoute = AuthenticatedWantlistRouteImport.update({
  id: '/wantlist',
  path: '/wantlist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionRoute = AuthenticatedCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWantlistIdRoute = AuthenticatedWantlistIdRouteImport.update({
  id: '/wantlist_/$id',
  path: '/wantlist/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionIdRoute =
  AuthenticatedCollectionIdRouteImport.update({
    id: '/collection_/$id',
    path: '/collection/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/wantlist': typeof AuthenticatedWantlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/collection/$id': typeof AuthenticatedCollectionIdRoute
  '/wantlist/$id': typeof AuthenticatedWantlistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/wantlist': typeof AuthenticatedWantlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/collection/$id': typeof AuthenticatedCollectionIdRoute
  '/wantlist/$id': typeof AuthenticatedWantlistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/_authenticated/collection': typeof AuthenticatedCollectionRoute
  '/_authenticated/wantlist': typeof AuthenticatedWantlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/_authenticated/collection_/$id': typeof AuthenticatedCollectionIdRoute
  '/_authenticated/wantlist_/$id': typeof AuthenticatedWantlistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/collection'
    | '/wantlist'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/collection/$id'
    | '/wantlist/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/collection'
    | '/wantlist'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/collection/$id'
    | '/wantlist/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/_authenticated/collection'
    | '/_authenticated/wantlist'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/_authenticated/collection_/$id'
    | '/_authenticated/wantlist_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wantlist': {
      id: '/_authenticated/wantlist'
      path: '/wantlist'
      fullPath: '/wantlist'
      preLoaderRoute: typeof AuthenticatedWantlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collection': {
      id: '/_authenticated/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof AuthenticatedCollectionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wantlist_/$id': {
      id: '/_authenticated/wantlist_/$id'
      path: '/wantlist/$id'
      fullPath: '/wantlist/$id'
      preLoaderRoute: typeof AuthenticatedWantlistIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collection_/$id': {
      id: '/_authenticated/collection_/$id'
      path: '/collection/$id'
      fullPath: '/collection/$id'
      preLoaderRoute: typeof AuthenticatedCollectionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCollectionRoute: typeof AuthenticatedCollectionRoute
  AuthenticatedWantlistRoute: typeof AuthenticatedWantlistRoute
  AuthenticatedCollectionIdRoute: typeof AuthenticatedCollectionIdRoute
  AuthenticatedWantlistIdRoute: typeof AuthenticatedWantlistIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCollectionRoute: AuthenticatedCollectionRoute,
  AuthenticatedWantlistRoute: AuthenticatedWantlistRoute,
  AuthenticatedCollectionIdRoute: AuthenticatedCollectionIdRoute,
  AuthenticatedWantlistIdRoute: AuthenticatedWantlistIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
